version: "3.7"
services:
  php:
    build:
      context: .
      target: ${TARGET:-production-pseudo}
    environment:
      MESSAGE: ${MESSAGE:-holla}
    working_dir: /app
    volumes:
      - .:/app
